_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 17
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
